### ISSUE TITLE
How to specify copies

### ISSUE THREAD

**Issue by letian-tang** [ArcticLampyrid/winprint.rs#1]
<psf:ParameterDef name="psk:JobCopiesAllDocuments">
        <psf:Property name="psf:DataType">
            <psf:Value xsi:type="xsd:QName">xsd:integer</psf:Value>
        </psf:Property>
        <psf:Property name="psf:UnitType">
            <psf:Value xsi:type="xsd:string">copies</psf:Value>
        </psf:Property>
        <psf:Property name="psf:Multiple">
            <psf:Value xsi:type="xsd:integer">1</psf:Value>
        </psf:Property>
        <psf:Property name="psf:MaxValue">
            <psf:Value xsi:type="xsd:integer">9999</psf:Value>
        </psf:Property>
        <psf:Property name="psf:MinValue">
            <psf:Value xsi:type="xsd:integer">1</psf:Value>
        </psf:Property>
        <psf:Property name="psf:DefaultValue">
            <psf:Value xsi:type="xsd:integer">1</psf:Value>
        </psf:Property>
        <psf:Property name="psf:Mandatory">
            <psf:Value xsi:type="xsd:QName">psk:Unconditional</psf:Value>
        </psf:Property>
        <psf:Property name="psk:DisplayName">
            <psf:Value xsi:type="xsd:string">份数</psf:Value>
        </psf:Property>
    </psf:ParameterDef>

**Comment by ArcticLampyrid** [comment]
Thanks for pointing that out. It's a simple feature that I missed due to not needing it myself. I'll add it when I have some free time, but it might take a while as I'm currently overrun.

**Comment by letian-tang** [comment]
> Thanks for pointing that out. It's a simple feature that I missed due to not needing it myself. I'll add it when I have some free time, but it might take a while as I'm currently overrun.

thanks
